### ISSUE TITLE
Improve transfer to human by mail

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/node#303]
There are 2 small improvements which can be done

- [x] At this time, when transferring to human by mail, 2 separate e-mails are sent: one with the history,  one with the question "Whats your response to the above messages?". It would be better to have just one.
- [ ] Since the e-mail contains the ID of the `user`in the quoted part, we don't need the human to specify the `user` ID(see #301 and discussion referenced there)

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev I see you've been trying to solve it yourself.
I just pushed my latest version, can you please check if it works for you?
If not, please add corresponding application logs, it may be helpful.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev FYI just restored webhook url, so after this point it's good to be tested again.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv Successfully tested, many thanks.
