### ISSUE TITLE
Implement "short answers" on channels which do not support quick answers

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/node#311]
Some `channels`such as Wechat or Cisco Spark currently do not support "quick answers" with buttons. For these channels, when "quick answers" have been defined in the conversational engine:

- [ ] Add a number and a dot before the choice (for example "1. Van Gogh")
- [ ] When the user enters a number as an answer, substitute the number with the corresponding choice

cc @Yurko-Fedoriv

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> So I will put a clarification here, that we want to support this feature for all channels

OK, got it, sorry. Yes, good idea.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> This is going to work like this: If bot receives numeric message from the user, it will search conversation for the latest bot's message with actions/cards+actions. If found, user's message with number will be replaced by appropriate postback (there is going to be a helper function to predictably map action numbers to actions). In case number in user's message can't be mapped to anything, it will be passed to AI as ususal. Do you foresee any issues with this approach?

Thanks for this suggestion. I think it's the correct approach, I don't see potential issues at this time. The only thing is that I would look only for the most recent message in the `user`'s history.

cc @ALLENWAN1

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev this is now implemented, you are welcome to test it out.
Please note, that action numbers for now will be visible only in WeChat channel, because every channel has it's own code for cards/actions representation. Please let me know in which channels you want to display action indexes.

Numeric responses will already work for any channel.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

>  this is now implemented, you are welcome to test it out.

Successfully tested, congrats. @ALLENWAN1 can you also test and confirm it looks fine ?

> Please let me know in which channels you want to display action indexes

In e-mail et Cisco Spark please.

**Comment by ALLENWAN1** [comment]
yes, it works well and looks fine.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev I added action indexes to email and spark channels.

Right now I don't know how to test spark locally, so I made a change that should work, but let me know how it looks.

I did test email channel, so I don't expect problems there, but please let me know if you find issues.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv Sorry for the delay, yesterday was a day off here. Successfully tested. Thanks.
