### ISSUE TITLE
imageAttachment url is truncated in wit context 

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/node#313]
@Yurko-Fedoriv 

We are struggling to get the Deepiks Painting server working again after the crash you reported in https://github.com/deepiksdev/node/issues/209#issuecomment-292781408 .

It seems that for some reason, the imageAttachment is now truncated in the `context`that ther node server is supposed to send to the Deepiks Painting server, which prevents the Deepiks Painting server to work properly.

For example:
```
https://deepiks-botdata.s3-eu-west-1.amazonaws.com/eu-west-1%3A9b648ba2-d018-4723-8b65-2710b3062119/52cceeb0-8ad8-11e6-bc96-c186c2efac62/331b21b1-1ea6-11e7-a080-af5d1ed82393/1491908561861_0.png
```
is truncated to 
```
https://deepiks-botdata.s3-eu-west-1.amazonaws.com/eu-west-1%3A9b648ba2-d018-4723-8b65-2710b3062119/52cceeb0-8ad8-11e6-bc96-c186c2efac62/331b21b1-1ea6
```

At this time, I don't know yet where this problem comes from:
- recent changes in our code ?
- recent changes in wit.ai ?

If you have ideas and possible solutions, it will be great. Otherwise, we'll keep investigating.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev I don't think it is caused by changes in our code. It did behave as expected while I was working on #209 on Thursday, and nothing was changed since then except READMEs.
You may try to restore any earlier version of the code, but I think it might be something on the wit.ai side. Won't harm to contact them, I guess.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv Thanks for your quick feedback. We keep investigating.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

FYI, truncation comes from https://github.com/deepiksdev/node/blob/ab206fe521e1a10b7a2cce0382f3e81b1e3f0908/src/server/deepiks-bot/ai/wit-ai.js#L228 , which has been implemented for some time. 

So, this is probably not the reason why the Painting Server is not working.

At this time, I don't understand:
- why truncation was implemented by @sean-shirazi 
- how this did not prevent Deepiks Painting from working

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv I have removed the truncation. Hopefully this will not generate problems, and we will understand later why Deepiks Painting worked with this truncation, and stopped working at the end of last week.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev truncation was actually done by me. Unfortunately I did not account that it is truncating in more cases than needed.
Wit.ai does not allow longer messages to be sent and triggers errors. I found this out during some testing of long emails.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev I made a change that should not affect image urls anymore. https://github.com/deepiksdev/node/commit/7561b51a0673798bb809789d58c7a8ce60ccbec9

Let me know what do you think.

**Comment by deepiksdev** [comment]
This looks fine, many thanks.
