### ISSUE TITLE
Site displays error 500 when browser language is not en or fr

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/node#315]
![2](https://cloud.githubusercontent.com/assets/2860170/25224861/0513a3ca-25c0-11e7-8c9c-ed4e4573b8af.jpeg)

One way to turn around this bug is to en or fr as secondary language.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv Can you please fix this ?

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev sure, I'll look into it shortly

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv Many thanks.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev should now be fixed.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv OK, many thanks !
