### ISSUE TITLE
Make it possible to send pictures instead of cards

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/node#316]
This will make sharing much easier.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev I will need more detailed description/specification to resolve this task. If possible, with some examples of what we are trying to achieve here.

**Comment by ogood** [comment]
@deepiksdev @Yurko-Fedoriv  this function requires a verified official account. but you can apply for a test account here, it's easy and simple: https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login  notice: the photo sent to a subscriber should <2MB

**Comment by deepiksdev** [comment]
@ogood Thanks for the tip.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> I will need more detailed description/specification to resolve this task. If possible, with some examples of what we are trying to achieve here.

At this time, we have no way to send a picture directly to the `user`as we might do if the bot was a regular `user`. For example, in Messenger, it's easy to send a picture to a friend, and when you receive a picture from a friend, it's easy to share it or to save it on your computer. 

In Messenger, for example, we could send pictures to the user as documented here: https://developers.facebook.com/docs/messenger-platform/send-api-reference/image-attachment .

We need to find a way to send images either directly from wit.ai. My suggestion would be that when the wit.ai message starts with `http://` and ends with `.png`or `.jpg`, then we send the corresponding content to the user as an image.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev Is it possible for you to set up test bot/dialog so I can develop this on top of it?
Your proposal with detecting an image url sounds good at the moment, I'll let you know if I come up with something else while developing this.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

>  Is it possible for you to set up test bot/dialog so I can develop this on top of it?
Your proposal with detecting an image url sounds good at the moment, I'll let you know if I come up with something else while developing this

Done in the [Deepiks Painting](https://github.com/deepiksdev/node/blob/master/README.md#example) bot . Simply enter "Send me original" to test.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev thank you

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev I tried to start with WeChat, since it was the most recent channel I worked with, but apparently it's not possible with subscription account: 

To send an image message I need to upload media first: http://admin.wechat.com/wiki/index.php?title=Callback_Messages#Image_Message (not hte media_id param)

To upload media I need to talk to the api. First step would be to get access token: http://admin.wechat.com/wiki/index.php?title=Access_token Doing this I get 
```
> curl 'https://api.wechat.com/cgi-bin/token?grant_type=client_credential&appid=wxd297229e4f049dc8&secret=5d45fd1da7cc5ae545c6ac34ee106355'
{"errcode":50001,"errmsg":"user unauthorized hint: [.Ni6hA0555e544]"}
```

Apparently subscription accounts only limited to the basic messaging api: 
![Official accounts of different types have different functions and permissions](https://admin.wechat.com/mpres/htmledition/images/en/faq_1_1_3.jpg)

Some related reference on stackowerflow https://stackoverflow.com/a/23002337/1779106

We do have appId/appSecret pair in our account, but they are no good to acquire api access token and do anything with it.

I can try to proceed in development mode, let me know if you want this, but I guess I'll switch to another channel for now.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev For facebook and other channels I need a development accounts access, can you give it to me please (fb.com/yurko.fedoriv)?

I'll try to setup new fb app for now, but I feel like having this access will be needed at some point anyway.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

Thanks for your feedback.

> I can try to proceed in development mode, let me know if you want this, but I guess I'll switch to another channel for now.

You can do both, at your convenience. Anyway, we'll need a service account at some point, and we are in the process of getting one.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> For facebook and other channels I need a development accounts access, can you give it to me please (https://fb.com/yurko.fedoriv)?

Done for Facebook, will give you access to Microsoft powered channels via private message.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev ok, since you gave me a fb development page, I'll switch to it. Looks, like it should not be complicated

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev added support for messenger, email and webchat. 
Also for transcripts page.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

>  added support for messenger, email and webchat.
Also for transcripts page.

Great, will test tomorrow

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> added support for messenger, email and webchat.

Successfully tested on Messenger. Congrats.

For some reason, webchat version does not display image on Safari.

cc @ALLENWAN1

**Comment by Yurko-Fedoriv** [comment]
That's odd. Have you tried cleaning safari browser cache?

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

>> For some reason, webchat version does not display image on Safari.

> That's odd. Have you tried cleaning safari browser cache?

It's OK now, sorry.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev no problem. glad it works.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev added support for ms and spark channels. Please let me know if it works ok.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 


> added support for ms and spark channels. Please let me know if it works ok.

Spark is OK, however ms (namely Skype) does not answer anymore to any user input.

![img_2380](https://cloud.githubusercontent.com/assets/2860170/26833447/c079153c-4ad2-11e7-8f80-01960aee8278.PNG)

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev does it work on the previous revision? I can't think how my change in MS channel  it can lead to this, but POST to the ms webhook times out for some reason.
Can you check what's going on on in logs?

```
> curl -XPOST -H 'Content-Type: application/json' -i https://deepiks.botplatform.cloud/webhooks/eu-west-1:9b648ba2-d018-4723-8b65-2710b3062119/52cceeb0-8ad8-11e6-bc96-c186c2efac62/ms -d '{}'
```

I checked local version with botframework emulator, and it works fine.
If we can't narrow down the problem, I'll redirect MS webhook to my local machine and see how it works.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 


> Can you check what's going on on in logs?

Here are the [logs](https://github.com/deepiksdev/node/files/1055405/TailLogs-1496760764780.txt) after running 

> > curl -XPOST -H 'Content-Type: application/json' -i https://deepiks.botplatform.cloud/webhooks/eu-west-1:9b648ba2-d018-4723-8b65-2710b3062119/52cceeb0-8ad8-11e6-bc96-c186c2efac62/ms -d '{}'

Sorry, I can't test the previous version for now.

Thanks !

**Comment by Yurko-Fedoriv** [comment]
Unfortunately logs you provided do not contain useful information.
Let's brainstorm on this when you are available.

I also can't login into MS account you provided because it wants email/phone verification.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev if there is a way to share bot application within dev.botframework.com my Microsoft login is also ```yurko.fedoriv@gmail.com```

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> if there is a way to share bot application within dev.botframework.com my Microsoft login is also yurko.fedoriv@gmail.com

Unfortunately, no.

I need to go for a meeting, but I will make other tests later and share info/comments with you. Thanks.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 


I have made additional tests, and accessed the logs directly on the server using `eb ssh`

After running

```
curl -XPOST -H 'Content-Type: application/json' -i https://deepiks.botplatform.cloud/webhooks/eu-west-1:9b648ba2-d018-4723-8b65-2710b3062119/52cceeb0-8ad8-11e6-bc96-c186c2efac62/ms -d '{}'
```

I got the following error:
```
Fri, 09 Jun 2017 22:17:12 GMT deepiks:ms ms-webhook raw req.headers:  { connection: 'upgrade',
  host: 'deepiks.botplatform.cloud',
  'x-real-ip': '172.31.39.83',
  'x-forwarded-for': '37.25.78.23, 172.31.39.83',
  'content-length': '2',
  'x-forwarded-proto': 'https',
  'x-forwarded-port': '443',
  'x-amzn-trace-id': 'Root=1-593b1e68-4397486d3fae1ebd0af3af47',
  'user-agent': 'curl/7.51.0',
  accept: '*/*',
  'content-type': 'application/json' }
Fri, 09 Jun 2017 22:17:12 GMT deepiks:aws getBot publisherId:  eu-west-1:9b648ba2-d018-4723-8b65-2710b3062119 , botId:  52cceeb0-8ad8-11e6-bc96-c186c2efac62
Fri, 09 Jun 2017 22:17:13 GMT deepiks:server-router:error The webhook of ms failed with error:  TypeError: Cannot read property 'ChatConnector' of undefined
    at Object.<anonymous> (/var/app/current/dist-server/webpack:/src/server/channels/ms.js:33:27)
    at tryCatch (/var/app/current/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/app/current/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/app/current/node_modules/regenerator-runtime/runtime.js:117:21)
    at r (/var/app/current/dist-server/webpack:/bundle.js:45301:188)
    at /var/app/current/dist-server/webpack:/bundle.js:45301:362
    at run (/var/app/current/node_modules/core-js/modules/es6.promise.js:87:22)
    at /var/app/current/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/var/app/current/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Does it help ?

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev wow. yes, this helps.
Apparently production pulled more fresh version of botbuilder and it slightly changed. I needed to make [such an adjustment](https://github.com/deepiksdev/node/commit/6de299f1af6c21757d4f95febbdca1874fd26a99#diff-cc72ad06dd388cddfc261878fa32358dR9) in how it is imported.

To avoid this I also added npm-shrinkwrap.json 

https://docs.npmjs.com/cli/shrinkwrap


Please try again. To be safe, delete/move node_modules entirely and then run ```npm i``` after pulling the latest version. Hope it works fine, please let me know,

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> Please try again. To be safe, delete/move node_modules entirely and then run npm i after pulling the latest version. Hope it works fine, please let me know

Done. Works fine, many thanks.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> I tried to start with WeChat, since it was the most recent channel I worked with, but apparently it's not possible with subscription account:
 [...]
 I can try to proceed in development mode, let me know if you want this, but I guess I'll switch to another channel for now.

FYI, we will have a service account opened probably this week. If you can finalize the work on the WeChat `channel`, it will be very useful.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev I'll try to work on it using dev mode.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> I'll try to work on it using dev mode.

Great, many thanks. cc @ALLENWAN1

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev I implemented wechat channel part. You can test it with sandbox account created here https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login
Unfortunately english sandbox only accepts british phone numbers, so we have to resort to using chinese one. When you get inside the test account, you can setup appropriate webhook and also you'll get AppID and Secret to put into bot settings. Make sure you are viewing original page when copying credentials, because google translate may corrupt them.

Then just scan "Test number two-dimensional code" with wechat, and you'll be able to talk to the bot.

Let me know if I should add account type to wechat bot setting, so I can make appropriate conditional stuff in the channel implementation, e.g. if API is unavailable, I'll just send the original link as text.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

Many thanks for this work.

> Let me know if I should add account type to wechat bot setting, so I can make appropriate conditional stuff in the channel implementation, e.g. if API is unavailable, I'll just send the original link as text.

No , I don't think so. I think we should support only service accounts for the time being.

Testing using the sandbox seems to be complicated. If you don't mind, let's wait for our service account to be approved (normally very soon) in order to perform tests.

cc @ogood @ALENWAN1

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev ok, no problem. Let's wait and see how it behaves live, anyway if there are any hidden issue they are more likely to be revealed this way.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv OK, many thanks.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv We just tested again on our Wechat bot. Trying to send an image results in a timeout. In order to reproduce, enter "请发送给我一张照片" . cc @ALLENWAN1

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv As discussed privately, the problem was that we needed to whitelist the IP address of our server. Thanks and congrats for fixing it. I think we can close this issue now. cc @ALLENWAN1
