### ISSUE TITLE
Implement Superscript

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/node#55]
This is a continuation of https://github.com/deepiksdev/microservices/issues/42 . 

@sean-shirazi As a first step, we need to check:
- [ ] Is the code clean and can it be installed on an Elastic Beanstalk instance without problem?
- [ ] One installed, is it working as expected?
- [ ] Can we use DynamoDB instead of MondgoDB (if yes, we will create another issue later to make the transition)?

**Comment by deepiksdev** [comment]
@ALLENWAN1 

I am reopening this issue because I successfully tested again superscript.

I belive we should implement it. I will provide more details later. Comments welcome.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

As discussed privately yesterday, I would like to know if we can include this package in this project, or if it should be implemented in a separate project, and invoked using websockets (or similar).

If you can take a quick look today and let us know, it will be very useful.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev we can include it in the project, but I have doubts we should. can you please tell me what would be the role of it at the current stage? 
Superscript has a strong dependency on mongodb and generally feels like something that aimed to be standalone. But again, there should not be any problems with integrating it directly to the app, it exposes JS api, and clients just read and proxy input from the corresponding source to this api.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv 

> we can include it in the project,

Thank you for this confirmation.

> can you please tell me what would be the role of it at the current stage?

Using wit.ai is not convenient for complex bots and contents. And it's not acceptable for enterprise customers.

> Superscript has a strong dependency on mongodb

We will implement MongoDB then. And maybe we should replace all DynamoDB uses with MongoDB.

Thank you again for your comments.

**Comment by Yurko-Fedoriv** [comment]
> And maybe we should replace all DynamoDB uses with MongoDB

Well, we definitely should weight on this, but this will involve a ton of refactoring.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv OK, let's close again this issue until further notice. Many thanks for looking into it.

cc @ALLENWAN1

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev just a note here: nothing stops us from having 2 databases in the project, or implementing superscript service standalone.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv

Thanks for your feedback.

 I agree, but I am worried about making our whole solution overly complicated.

And I have also identified other issues with Superscript:
- It does not support Markdown
- it does not support cards
- it is difficult to use for non technical people
- it works only in English, and requires a lot of work to be usable in other languages

So, all in all, I think it's a bad idea for now.

**Comment by Yurko-Fedoriv** [comment]
@deepiksdev agreed, sounds reasonable.

**Comment by deepiksdev** [comment]
@Yurko-Fedoriv FYI, we are working on [Rasa-NLU](https://github.com/deepiksdev/rasa_nlu), as a substitute to wit. Thanks again.
